---
- name: install nginx
  yum: pkg=nginx state=present

- name: configure SELinux for nginx
  seboolean: name=httpd_can_network_connect state=yes persistent=yes

- name: enable nginx systemd service
  service: name=nginx state=started enabled=yes